name: bigmarket
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Se agrego la libreria flutter_bloc para la implementación del patron bloc si no tiene la versión instala la mas actual
  flutter_bloc: 
  #ni idea para que esta linea 
  firebase_core:
  cupertino_icons: ^0.1.3
  #para implementar la autenticación con firebase
  firebase_auth: 
  #para implementar el logueo con la api google
  google_sign_in: 
  equatable: 
  meta: 
  cloud_firestore:
  #TODO detallar para que es esta libreria (?)
  rxdart:
  #esto solo es para utilizar fuentes 
  font_awesome_flutter:
  


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
#se habilita la opcion de usar iconos con la libreria material.dart(default)
  uses-material-design: true
#se habilita los accesos a la direccioin asset para la busqueda de imagenes (agregado)
  assets:
  - assets/
  - assets/icons/

  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
  - family: NunitoSans
    fonts:
    - asset: fonts/NunitoSans-Regular.ttf